#项目启动端口
server:
  port: 8080

#数据源配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/family_service_platform?serverTimezone=UTC
    password: root
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver

#配置mybatis
mybatis:
  mapper-locations: classpath:com/tyc/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

#sql语句打印 配置debug
logging:
  level:
    com:
      tyc:
        mapper: debug
